const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.AJAX,
		C3.Plugins.progressbar,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Internationalization,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.progressbar.Acts.SetVisible,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Internationalization.Acts.SetLocale,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup
	];
};
self.C3_JsPropNameTable = [
	{Esmaecer: 0},
	{tx_simples2: 0},
	{tx_simples: 0},
	{tx1: 0},
	{tx2: 0},
	{tx3: 0},
	{tx4: 0},
	{tx5: 0},
	{tx6: 0},
	{tx7: 0},
	{tx8: 0},
	{tx9: 0},
	{tx10: 0},
	{tx11: 0},
	{tx12: 0},
	{tx13: 0},
	{tx14: 0},
	{tx15: 0},
	{tx16: 0},
	{tx17: 0},
	{tx18: 0},
	{tx19: 0},
	{tx20: 0},
	{bt_concluir: 0},
	{bt_entendi: 0},
	{bt_entrar: 0},
	{bt_OK: 0},
	{Senóide: 0},
	{home: 0},
	{reniciar: 0},
	{Piscar: 0},
	{bg_vazio_1: 0},
	{bg_vazio_2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{pi_vision_after: 0},
	{check_in: 0},
	{bg_vazio_3: 0},
	{bt_transparente: 0},
	{bt_brasil: 0},
	{bt_china: 0},
	{bt_espanha: 0},
	{bt_italia: 0},
	{bt_usa: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite16: 0},
	{pi_vision_before: 0},
	{AJAX: 0},
	{barraLoad: 0},
	{inputBox: 0},
	{Mouse: 0},
	{Navegador: 0},
	{seta: 0},
	{Teclado: 0},
	{tradutor: 0},
	{tx_1: 0},
	{tx_OK: 0},
	{tx_OK2: 0},
	{Texto: 0},
	{bandeiras: 0},
	{IdiomaSelecionado: 0}
];

self.InstanceType = {
	tx_simples2: class extends self.ITextInstance {},
	tx_simples: class extends self.ITextInstance {},
	tx1: class extends self.ITextInstance {},
	tx2: class extends self.ITextInstance {},
	tx3: class extends self.ITextInstance {},
	tx4: class extends self.ITextInstance {},
	tx5: class extends self.ITextInstance {},
	tx6: class extends self.ITextInstance {},
	tx7: class extends self.ITextInstance {},
	tx8: class extends self.ITextInstance {},
	tx9: class extends self.ITextInstance {},
	tx10: class extends self.ITextInstance {},
	tx11: class extends self.ITextInstance {},
	tx12: class extends self.ITextInstance {},
	tx13: class extends self.ITextInstance {},
	tx14: class extends self.ITextInstance {},
	tx15: class extends self.ITextInstance {},
	tx16: class extends self.ITextInstance {},
	tx17: class extends self.ITextInstance {},
	tx18: class extends self.ITextInstance {},
	tx19: class extends self.ITextInstance {},
	tx20: class extends self.ITextInstance {},
	bt_concluir: class extends self.ISpriteInstance {},
	bt_entendi: class extends self.ISpriteInstance {},
	bt_entrar: class extends self.ISpriteInstance {},
	bt_OK: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	reniciar: class extends self.ISpriteInstance {},
	bg_vazio_1: class extends self.ISpriteInstance {},
	bg_vazio_2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	pi_vision_after: class extends self.ISpriteInstance {},
	check_in: class extends self.ISpriteInstance {},
	bg_vazio_3: class extends self.ISpriteInstance {},
	bt_transparente: class extends self.ISpriteInstance {},
	bt_brasil: class extends self.ISpriteInstance {},
	bt_china: class extends self.ISpriteInstance {},
	bt_espanha: class extends self.ISpriteInstance {},
	bt_italia: class extends self.ISpriteInstance {},
	bt_usa: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	pi_vision_before: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	barraLoad: class extends self.IProgressBarInstance {},
	inputBox: class extends self.ITextInputInstance {},
	Mouse: class extends self.IInstance {},
	Navegador: class extends self.IInstance {},
	seta: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	tradutor: class extends self.IInstance {},
	tx_1: class extends self.ITextInstance {},
	tx_OK: class extends self.ITextInstance {},
	tx_OK2: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	bandeiras: class extends self.ISpriteInstance {}
}